TrajectoryPlannerROS:
    # Robot Configuration Parameters
    acc_lim_x: 1.5
    acc_lim_y: 0.0
    acc_lim_theta: 1.5
    max_vel_x: 0.5
    min_vel_x: 0.1
    max_vel_y: 0.0
    min_vel_y: 0.0
    max_vel_theta: 1.0
    min_vel_theta: -1.0
    max_rotational_vel: 2.0
    min_in_place_rotational_vel: 0.5
    escape_vel: -0.1
    holonomic_robot: false

    # Goal Tolerance Parameters
    xy_goal_tolerance: 0.1
    yaw_goal_tolerance: 0.1
    latch_xy_goal_tolerance: true

    # Forward Simulation Parameters
    sim_time: 1.5
    sim_granularity: 0.05
    angular_sim_granularity: 0.05
    #vx_samples: 5
    #vtheta_samples: 20
    controller_frequency: 20

    # Trajectory Scoring Parameters    
    meter_scoring: true
    gdist_scale: 0.9
    pdist_scale: 0.8
    goal_distance_bias: 0.9
    #path_distance_bias: 3.0
    #occdist_scale: 0.01
    #heading_lookahead: 0.325
    #heading_scoring: 1
    #heading_scoring_timestep: 0.8
    
    dwa: false
    #publish_cost_grid_pc: false
    #global_frame_id: odom

    # Oscillation Prevention Parameters, 0.5 idi
    #oscillation_reset_dist: 0.5
