map_type: costmap
meter_scoring: true
transform_tolerance: 0.5
obstacle_range: 7.5
raytrace_range: 8.0
robot_base_frame: base_footprint
#footprint: [[-0.315, -0.265], [0.315, -0.265], [0.315, 0.265], [-0.315, 0.265]]
#robot_radius: ir_of_robot
#footprint: [[0.1995, -0.2635], [0.2605, -0.2275], [0.2965, -0.1735], [0.3145, -0.0515], [0.3145, 0.0515], [0.2965, 0.1735], [0.2605, 0.2275], [0.1995, 0.2635], [-0.1995, 0.2635], [-0.2605, 0.2275], [-0.2965, 0.1735], [-0.3145, 0.0515], [-0.3145, -0.0515], [-0.2965, -0.1735], [-0.2605, -0.2275], [-0.1995, -0.2635]]
#inflation_radius: 0.3
footprint: [[-0.315, -0.14], [-0.315, 0.14], [-0.22, 0.265], [0.22, 0.265], [0.315, 0.14], [0.315, -0.14], [0.22, -0.265], [-0.22, -0.265]]
footprint_padding: 0.01

plugins:
- {name: static_layer, type: "costmap_2d::StaticLayer"}
- {name: obstacles_layer, type: "costmap_2d::ObstacleLayer"}
- {name: inflation_layer, type: "costmap_2d::InflationLayer"}

obstacles_layer:
   track_unknown_space:  true
   observation_sources: scan
   scan: {sensor_frame: /base_laser_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}
#- {name: sonar_layer, type: "range_sensor_layer::RangeSensorLayer"}

inflation_layer:
  enabled:              true
  cost_scaling_factor:  5.0
  inflation_radius:     0.5
#sonar_layer:
#  topics: ["/sonar_1","/sonar_2","/sonar_3","/sonar_4","/sonar_5","/sonar_6","/sonar_7"]
#  clear_on_max_reading: true
#  no_readings_timeout: 1.0
