map_type: costmap
meter_scoring: true

obstacle_range: 8.0
raytrace_range: 10.0
footprint: [[-0.315, -0.265], [0.315, -0.265], [0.315, 0.265], [-0.315, 0.265]]
#robot_radius: ir_of_robot
inflation_radius: 0.5

observation_sources: scan

scan: {sensor_frame: /base_laser_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}

