#Independent settings for the planner's costmap
global_costmap:
    global_frame: odom
    robot_base_frame: base_footprint
    update_frequency: 1.0
    publish_frequency: 1.0
    static_map: false
    rolling_window: true
    unknown_cost_value: 75
