shutdown_costmaps: false

controller_frequency: 10.0
controller_patience: 5.0

planner_frequency: 0.5
planner_patience: 3.0

oscillation_timeout: 10.0
oscillation_distance: 0.2

recovery_behavior_enabled: true
clearing_rotation_allowed: true

conservative_reset_dist: 1.0

recovery_behaviors:
  - name: 'conservative_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'aggressive_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'

conservative_reset:
  reset_distance: 3.0

aggressive_reset:
  reset_distance: 0.0