global_costmap:
<<<<<<< HEAD
   transform_tolerance: 1.0
=======
>>>>>>> aafa4458de2eefb216e61a207784001db52db09e
   global_frame: map
   robot_base_frame: base_footprint
   update_frequency: 0.5
   publish_frequency: 10.0
   width: 40.0
   height: 40.0
   resolution: 0.05
   origin_x: -20.0
   origin_y: -20.0
<<<<<<< HEAD
   static_map: false
   rolling_window: true

   inflation_layer:
     inflation_radius: 0.4
=======
   static_map: true
   rolling_window: false

   inflater_layer:
     inflation_radius: 0.7
>>>>>>> aafa4458de2eefb216e61a207784001db52db09e
