global_costmap:
   global_frame: map
   robot_base_frame: base_footprint
   update_frequency: 2.0
   publish_frequency: 1.0
   width: 40.0
   height: 40.0
   resolution: 0.05
   origin_x: -20.0
   origin_y: -20.0
   static_map: true
   rolling_window: false
   transform_tolerance: 0.5

   inflation_layer:
     inflation_radius: 0.5
