local_costmap:
<<<<<<< HEAD
   transform_tolerance: 0.5
=======
>>>>>>> aafa4458de2eefb216e61a207784001db52db09e
   global_frame: map
   robot_base_frame: base_footprint
   update_frequency: 10.0
   publish_frequency: 10.0
   width: 10.0
   height: 10.0
   resolution: 0.05
   static_map: false
   rolling_window: true
<<<<<<< HEAD

=======
   
>>>>>>> aafa4458de2eefb216e61a207784001db52db09e
   inflation_layer:
      inflation_radius: 0.2
