two_d_mode: true
frequency: 50

odom_frame: odom
base_link_frame: base_footprint

odom0: /mobile_base_controller/odom
odom0_config: [true, true, true,
               false, false, false,
               false, false, false,
               false, false, true,
               false, false, false]
odom0_differential: true

imu0: imu/data
imu0_config: [false, false, false,
              true, true, true,
              false, false, false,
              true, true, true,
              true, true, true]
imu0_differential: false
